version: "3.8"

services:
  postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
